org.gradle.jvmargs=-Xmx512m -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx512m
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=36

# === Credenciales de la app (NO commitear si se mueve a otro repo) ===
monitorEmail=monitor@siemprecerca.app
monitorPassword=M0n1t0rSC2026
webhookSecret=4d60192711902e66a26923bfc375cb73
keystorePassword=SiempreCerca2026Release
